# Generated by Django 5.1.15 on 2026-06-02 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('careers_url', models.URLField(blank=True)),
                ('ats_provider', models.CharField(blank=True, choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby'), ('workable', 'Workable'), ('smartrecruiters', 'SmartRecruiters'), ('jsearch', 'JSearch'), ('manual', 'Manual')], max_length=20)),
                ('ats_company_slug', models.CharField(blank=True, max_length=255)),
                ('scrape_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('detecting', 'Detecting')], default='active', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Watchlist companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(default=list)),
                ('locations', models.JSONField(default=list)),
                ('job_types', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='watchlist.watchlistcompany')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('description_text', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reposted', models.BooleanField(default=False)),
                ('matched_rules', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='watchlist.watchlistcompany')),
            ],
            options={
                'ordering': ['-first_seen_at'],
                'unique_together': {('company', 'external_id')},
            },
        ),
    ]
