# Generated by Django 5.1.15 on 2026-06-02 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('job_description', models.TextField(blank=True)),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude')], max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('prompt_settings', models.JSONField(blank=True, default=dict)),
                ('version_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='applications.application')),
                ('cv_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.cvversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('cover_letter', 'Cover Letter'), ('qa', 'Question Answer'), ('fit_score', 'Fit Score'), ('ats_score', 'ATS Score'), ('suggestions', 'Suggestions')], max_length=20)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'feature', 'timestamp'], name='ai_aiusagel_user_id_8b66e3_idx')],
            },
        ),
    ]
