# Generated by Django 5.1.15 on 2026-06-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('internship', 'Internship'), ('coop', 'Co-op'), ('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('contract', 'Contract')], max_length=20)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('oa_assessment', 'OA/Assessment'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview'), ('final_round', 'Final Round'), ('offer_received', 'Offer Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted')], default='saved', max_length=20)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('handshake', 'Handshake'), ('indeed', 'Indeed'), ('direct', 'Direct'), ('referral', 'Referral'), ('career_fair', 'Career Fair'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('ai_fit_score', models.IntegerField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('recruiter_name', models.CharField(blank=True, max_length=255)),
                ('recruiter_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_change', 'Status Change'), ('note_added', 'Note Added'), ('updated', 'Updated'), ('follow_up_set', 'Follow Up Set')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='cvs/')),
                ('file_size', models.IntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('parsed_json', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
